language: java
jdk:
    - oraclejdk8
before_script:
    - mysql -e 'CREATE DATABASE sigest_db'
    - mysql -e 'CREATE DATABASE sigest_db_test'

    - mysql -e "CREATE USER 'sigest_user'@'localhost' IDENTIFIED BY 'sigest_user';"

    - mysql -e "GRANT ALL ON sigest_db.* TO 'sigest_user'@'localhost';"
    - mysql -e "GRANT ALL ON sigest_db_test.* TO 'sigest_user'@'localhost';"
services:
    - mysql
cache:
  directories:
    - '$HOME/.m2/repository'

